name = "Zenarchist's Broken Glasses Mod"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "Zenarchist's Broken Glasses Mod"; // tool tip on mouse hover
overview = "Adds broken glass effect to damaged optics/glasses."; // overview
action = "https://zenarchist.io/"; // link
author = "Zenarchist"; // author
version = "1.0"; // version